import React from 'react'
import Nav from '../components/Nav'
import '../styles/globals.css'
import { Provider } from 'react-redux'
import store from '../redux/Store'
import { PersistGate } from 'redux-persist/lib/integration/react'
import { persistor } from '../redux/Store'
import Head from 'next/head'
import Script from 'next/script'
import Footer from '../components/Footer'

function MyApp({ Component, pageProps }) {
  return <>
    <Head>
      <title>Fashion store</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    {/* razorpay link */}
    <Script src="https://checkout.razorpay.com/v1/checkout.js"></Script>

    <Provider store={store}>
      <PersistGate persistor={persistor} loading={null}>
        <React.Fragment>
          <Nav />
          <Component {...pageProps} className = 'bodyWidth'/>
          {/* <Footer/> */}
        </React.Fragment>
      </PersistGate>
    </Provider>
  </>
}

export default MyApp
