import React from 'react'
import Nav from '../components/Nav'
import '../styles/globals.css'
import { Provider } from 'react-redux'
import store from '../redux/Store'
import { PersistGate } from 'redux-persist/lib/integration/react'
import { persistor } from '../redux/Store'
import Head from 'next/head'
import Script from 'next/script'

function MyApp({ Component, pageProps }) {
  return <>
    <Head>
      <title>Fashion store</title>
      <meta name="description" content="Generated by create next app" />
      {/* <link rel="icon" href="/favicon.ico" /> */}
      {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /> */}

      {/* google font link */}
      {/* <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Lobster+Two&display=swap" rel="stylesheet" /> */}

      {/* font awesome link */}
      {/* <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" /> */}

    </Head>
    {/* razorpay link */}
    <Script src="https://checkout.razorpay.com/v1/checkout.js"></Script>

    <Provider store={store}>
      <PersistGate persistor={persistor} loading={null}>
        <React.Fragment>
          <Nav />
          <Component {...pageProps} />
        </React.Fragment>
      </PersistGate>
    </Provider>
  </>
}

export default MyApp
